### ISSUE TITLE
Query Clone functionality needed

### ISSUE THREAD

**Issue by ctcforce** [jongpie/NebulaQueryAndSearch#45]
I have a usecase where I want to create a Nebula Query instance, call a series of common method invocations on the Query, then clone the Query so I can proceed to make varying method invocations on the two versions.

Currently in order to get two Query objects that share a common core structure but vary in other ways is to manually build each Query from the ground up.

**Comment by jamessimone** [comment]
@ctcforce you should be able to do this today - `clone()` is an OOTB method:

```java
Nebula.Query first = new Nebula.Query(Schema.User.SObjectType).limitTo(1);

Nebula.Query clone = first.clone();
clone.limitTo(2);

System.debug(first.getQuery());  // outputs SELECT Id, Name FROM User LIMIT 1
System.debug(clone.getQuery());  // outputs SELECT Id, Name FROM User LIMIT 2
```
